version: '3.8'

services:
  app:
    container_name: cf-stocks-app
    image: cf-stocks-app
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
