version: '3.8'

services:
  app:
    container_name: vite-client
    image: vite-client
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
